trigger:
  - main

resources:
  - repo: self

pool:
  name: befit-nutrition-pool

steps:
  - script: echo $(BuildVersion) # display BuildVersion
  - script: echo $(Build.BuildNumber) #display Run Number
  - task: EnvTransform@0
    inputs:
      inputType: 'file'
      inputFile: '$(Build.SourcesDirectory)/.env.release'
      outputFile: '$(Build.ArtifactStagingDirectory)/.env'
  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Build.SourcesDirectory)
      Contents: |
        **/*
        !.git/**/*
        !node_modules/**/*
        !dist/*
        !logs/*
      TargetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: befit-nutrition-cms.$(Build.BuildNumber)